version: '2'
services:
    jhipster10062018-app:
        image: jhipster10062018
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipster10062018-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipster10062018
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster10062018-mongodb:
        extends:
            file: mongodb.yml
            service: jhipster10062018-mongodb
