version: '2'
services:
    jhipster10062018-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipster10062018/mongodb/:/data/db/
